"""Initial PostgreSQL schema — all 8 SRS tables.

Revision ID: 63207e50c596
Revises:
Create Date: 2026-07-08 12:51:58.426539

This migration was autogenerated from app.db.models and creates:

  repositories          — stable repo identity (GitHub or zip)
  analysis_jobs         — one row per analysis run
  files                 — per-job file index
  dependencies          — directed edges between files
  node_scores           — PageRank / betweenness / composite_score
  cycles + cycle_members — normalized circular dependency storage
  analysis_statistics   — cached counts and graph density

Apply with:  cd backend && alembic upgrade head
Rollback with: alembic downgrade base
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "63207e50c596"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- Core identity: repo → job ---
    op.create_table(
        "repositories",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("owner", sa.Text(), nullable=True),
        sa.Column("repo_name", sa.Text(), nullable=False),
        sa.Column("branch", sa.Text(), nullable=True),
        sa.Column("commit_sha", sa.Text(), nullable=True),
        sa.Column("default_branch", sa.Text(), nullable=True),
        sa.Column("file_hash", sa.Text(), nullable=True),
        sa.Column("analysis_version", sa.Text(), server_default=sa.text("'1'"), nullable=False),
        sa.Column("created_by", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_hash"),
        sa.UniqueConstraint("owner", "repo_name", "branch", postgresql_nulls_not_distinct=True),
    )
    op.create_table(
        "analysis_jobs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("error_msg", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["repo_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_analysis_jobs_repo", "analysis_jobs", ["repo_id"], unique=False)

    # --- Job outputs: stats, cycles, files ---
    op.create_table(
        "analysis_statistics",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("file_count", sa.Integer(), nullable=False),
        sa.Column("node_count", sa.Integer(), nullable=False),
        sa.Column("edge_count", sa.Integer(), nullable=False),
        sa.Column("cycle_count", sa.Integer(), nullable=False),
        sa.Column("external_dependency_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("class_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("function_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("graph_density", sa.Float(), nullable=True),
        sa.Column("computed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["analysis_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_table(
        "cycles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("length", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["analysis_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "files",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("language", sa.Text(), server_default=sa.text("'python'"), nullable=False),
        sa.Column("line_count", sa.Integer(), nullable=True),
        sa.Column("syntax_error", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["analysis_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "file_path"),
    )
    op.create_index("idx_files_job", "files", ["job_id"], unique=False)

    # --- Graph detail: cycle membership, edges, scores ---
    op.create_table(
        "cycle_members",
        sa.Column("cycle_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["cycle_id"], ["cycles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("cycle_id", "position"),
        sa.UniqueConstraint("cycle_id", "file_id"),
    )
    op.create_index("idx_cycle_members_file", "cycle_members", ["file_id"], unique=False)
    op.create_table(
        "dependencies",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("source_file_id", sa.UUID(), nullable=False),
        sa.Column("target_file_id", sa.UUID(), nullable=False),
        sa.Column("dependency_type", sa.Text(), server_default=sa.text("'import'"), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["analysis_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_file_id"], ["files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "source_file_id", "target_file_id", "dependency_type"),
    )
    op.create_table(
        "node_scores",
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("pagerank_score", sa.Float(), nullable=False),
        sa.Column("betweenness_score", sa.Float(), nullable=False),
        sa.Column("composite_score", sa.Float(), nullable=False),
        sa.Column("in_degree", sa.Integer(), nullable=False),
        sa.Column("out_degree", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["analysis_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("file_id"),
    )
    op.create_index(
        "idx_node_scores_composite",
        "node_scores",
        ["composite_score"],
        unique=False,
        postgresql_ops={"composite_score": "DESC"},
    )


def downgrade() -> None:
    # Drop in reverse dependency order (children before parents)
    op.drop_index("idx_node_scores_composite", table_name="node_scores", postgresql_ops={"composite_score": "DESC"})
    op.drop_table("node_scores")
    op.drop_table("dependencies")
    op.drop_index("idx_cycle_members_file", table_name="cycle_members")
    op.drop_table("cycle_members")
    op.drop_index("idx_files_job", table_name="files")
    op.drop_table("files")
    op.drop_table("cycles")
    op.drop_table("analysis_statistics")
    op.drop_index("idx_analysis_jobs_repo", table_name="analysis_jobs")
    op.drop_table("analysis_jobs")
    op.drop_table("repositories")
